---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: fedora-20
  driver_config:
    box: fedora-20
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-20_chef-provisionerless.box
  customize:
    memory: 4096
    cpus: 2
suites:
- name: default
  run_list: ["recipe[nupic]"]
  attributes: {}
